version: "3.7"

services:
  app:
    context: . #крапка вказує, що сервіс створить апку з Dockerfile, що знаходиться в тій же директорії (на тому ж рівні, що і даний файл)
  ports:
    - "8000:8000" #ліва сторона - як буде джанго запускатися на локальній машині, а права - як на віртуальній
  volumes:  #наче дзеркало, яке вказує на віртуальні і локальні папки, якшо щось змінить в одній, то автоматично зміниться і в іншій
    - ./backend:/app  #локальна папка backend буде дзеркалювати з віртуальною, створеною на крок раніше, папкою app
  env_file:

