# Generated by Django 3.2.5 on 2021-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='brand_name',
            field=models.CharField(choices=[('N', 'Nissan'), ('B', 'BMW'), ('A', 'Audi'), ('F', 'Ford')], default='N', max_length=1),
        ),
    ]
