# Generated by Django 3.2.7 on 2021-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carmodel_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
