# Generated by Django 3.2.5 on 2021-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'car'},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
