# Generated by Django 3.2.5 on 2021-08-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210812_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
