# Generated by Django 3.2.7 on 2021-10-09 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profilemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(upload_to=backend.core.services.upload_photo.upload_to),
        ),
        migrations.CreateModel(
            name='AutoClubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(db_table='users_autoclubs', related_name='auto_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_club',
            },
        ),
    ]
